baseURL = "//petethegoat.github.io/MMC-LandingPage"
languageCode = "en-us"
publishDir = "docs"
theme = "resdayn"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

[params]
	title = "Morrowind Modding Community"
	favicon = "favicon.ico"